config/routes.rb
Rails.application.routes.draw do
  resources :professors do
      resource :classrooms , only:[:new,:create]
  end
  resources :students do
      post 'check_register_number', on: :collection
      resource :classrooms , only:[:new,:create]

  end
  resources :courses  do
     post 'checkName', on: :collection
  end
  root to: 'students#index'

  

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :person , polymorphic: true
  belongs_to :course
  accepts_nested_attributes_for :person
  validates_uniqueness_of :person_id , scope: [:course_id , :person_type]
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :students, through: :classrooms , source: :person , source_type: "Student"
  has_many :professors, through: :classrooms , source: :person , source_type: "Professor"
  validates :name ,presence: true , uniqueness: true
  validates :status , numericality: true

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attachment :image
  validates :name ,presence: true
  validates :register_number , uniqueness: true , numericality: true , presence: true
  validates :status , numericality: true
  has_many :classrooms ,as: :person , dependent: :destroy
  has_many :courses, through: :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
    attachment :image
    validates :name ,presence: true
    validates :register_number , uniqueness: true , numericality: true
    validates :status , numericality: true
    has_many :classrooms ,as: :person , dependent: :destroy
    has_many :courses,   through: :classrooms 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :get_person , only: [:new , :create]
  def index

  end

  def new
    @classroom =  Classroom.new
    @courses = Course.all()
  end
  def create
   @courses = Course.all()
   @classroom = @person.classrooms.build(classroom_params)
   if @classroom.save
     redirect_to @person
   else
     render 'new'
   end
 end

 private
   def get_person
     if params.has_key?(:student_id)
       @person = Student.find(params[:student_id])
     else
       @person = Professor.find(params[:professor_id])
    end
  end

  private
    def classroom_params
      params.require(:classroom).permit(:entry_at , :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.eager_load(:students ,:professors )
  end

  def show
    @course = Course.find(params[:id])
    render json: @course
end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
   @course = Course.new(course_params)
   if @course.save
     redirect_to @course
   else
     render 'new'
   end
  end

  def update
  @course = Course.find(params[:id])

  if @course.update(course_params)
    redirect_to @course
  else
    redirect_to back
  end
end

  def checkName
    @name = params[:name]
    @course = Course.where(name:@name).first
    respond_to do |format|
    format.json {
        render json: {:course => @course}
     }
     end
  end
  def destroy
   @course = Course.find(params[:id])
   @course.destroy

   redirect_to courses_path
  end

  private
   def course_params
     params.require(:course).permit(:name, :description,:status)
   end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

   def about
   end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :register_number, :status, :formation ,:image)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
   end

  def new
    @student = Student.new
   end

  def edit
    @student = Student.find(params[:id])
   end


  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def check_register_number
    @register_number = params[:register_number]
    @student = Student.where(register_number:@register_number).first
    respond_to do |format|
    format.json {
        render json: {:student => @student}
     }
     end
  end
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end

  def update
  @student = Student.find(params[:id])

  if @student.update(student_params)
    redirect_to @student
  else
    render "edit"
  end
end

  private
    def student_params
      params.require(:student).permit(:name, :register_number,:status,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def dispatcher_tag
controller_name = controller.class.name.underscore
controller_name.gsub!(/\//, "_")
controller_name.gsub!(/_controller$/, "")

div_tag = %(dispatcher="#{controller_name}.#{controller.action_name}")

div_tag.html_safe
end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/new.html.erb
<h1><%=@person.name %> </h1>
<%= image_tag attachment_url(@person, :image, :fill, 200, 200, format: "jpg") , class:"img-responsive col-md-4" %>
<%= form_for(@classroom , url:[@person ,@classroom],html:{class:"form"}) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>
   <h2>Associar a Curso </h2>




 </div >
  <div class ="field">
   <%= f.label :course %><br>
   <%= f.collection_select :course_id, @courses, :id, :name, {:multiple => true}, class:"form-control" %>
 </div>
  <div class ="field">
  <%= f.label :Data %><br>
  <%= f.text_field :entry_at, class:"form-control" , id:"datetime"%>
</div>
  <p></p>
  <div class="actions">
    <%= f.submit class: "submit", value:"matricular" %>
  </div>
<% end %>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :status %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1><%= @course.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing courses</h1>




    <% @courses.each do |course| %>
      <div class="course" id="<%= course.id %>">
      <h3 class="course-title"><%= link_to "#{course.name}" , "#" %></h3>
        <div class="course-description"><%= course.description %></div>
        <div class="course-person" ></div>
      </div>



        <%= link_to  edit_course_path(course) do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>

        <%= link_to  course, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove"></span>
      <% end %>



    <% end %>


<br>

<%= link_to 'New course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>

<div class="course-person">
   <div class="course-professor">
      <h3>Professores</h3>
      <%= render partial: "persons/index",locals: {persons: @course.professors}%>
   </div>
   <div class="course-professor">
      <h3>Students</h3>
      <%= render partial: "persons/index",locals: {persons: @course.students}%>
   </div>
</div>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Students', root_path %></li>
<li><%= link_to 'Courses', courses_path %></li>
<li><%= link_to 'Professors', professors_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Escola" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Escola" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body <%= dispatcher_tag %>>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>

       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/persons/_index.html.erb
<div class="container-flex-row">
<% persons.each do |person| %>
  <div class="person">
    <h3 class="person-title"><%= link_to person.name, person %></h3>
    <%= image_tag attachment_url(person, :image, :fill, 200, 200, format: "jpg") %>
    <div><%= person.register_number %></div>
    <div><%= person.status %></div>
    <div><%= link_to 'Register', [:new,person,Classroom.new] %>
     <%= link_to   [:edit , person] do %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>

    <%= link_to person, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove"></span>
  <% end %>
</div>
  </div>
<% end %>
</div>

app/views/persons/_show.html.erb
<%= image_tag attachment_url(person, :image, :fill, 200, 200, format: "jpg") %>
<p>
  <strong>Name:</strong>
  <%= person.name %>
</p>

<p>
  <strong>Register number:</strong>
  <%= person.register_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= person.status %>
</p>
<p>
  <strong>Courses:</strong>

   <% person.courses.each do |course| %>
      </br>
      <strong><%= link_to "#{course.name}" , course_path(course)  %></strong>

     <% end %>

app/views/professors/_form.html.erb
<%= simple_form_for(@professor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :register_number %>
    <%= f.input :status , validate: true , maxlength:10%>
    <%= f.input :formation %>
  </div>
  <input id="uploadFile" placeholder="Choose File" disabled="disabled" />
  <div class="fileUpload btn btn-primary">
     <span>Upload</span>
 <%= f.attachment_field :image %>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Professors</h1>


    <%= render partial: "persons/index",locals: {persons:@professors}%>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "persons/show",locals: {person: @professor}%>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name , validate: true %>
    <%= f.input :register_number %>
    <%= f.input :status , validate: true%>

  </div>
  <input id="uploadFile" placeholder="Choose File" disabled="disabled" />
  <div class="fileUpload btn btn-primary">
     <span>Upload</span>
 <%= f.attachment_field :image %>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing students</h1>


  <%= render partial: "persons/index",locals: {persons: @students}%>

<br>

<%= link_to 'New student', new_student_path %>

app/views/students/new.html.erb
<h2 >New student</h2>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

  <%= render partial: "persons/show",locals: {person: @student}%>
 </p>
<%= link_to 'Edit', edit_student_path(@student) %>
<%= link_to 'Back', students_path %>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>A Bootstrap Starter Template</h1>
            <p class="lead">A Bootstrap HTML starter template from <a href="http://startbootstrap.com/">startbootstrap.com</a>.</p>
            <ul class="list-unstyled">
                <li>Bootstrap</li>
                <li>jQuery</li>
            </ul>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->